name: Test Action

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Local Action
        uses: ./
        with:
          app-id: ${{ secrets.FASTAPI_CLOUD_APP_ID }}
          token: ${{ secrets.FASTAPI_CLOUD_TOKEN }}
          work-dir: "./tests/dummy-app/src/app"
          not-wait: "true"
